# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# whenever the team pushes a change to the main branch of your repo or creates a pull request.
trigger:
- main

# runs on a Microsoft-hosted Linux machine
pool:
  #vmImage: ubuntu-latest
  vmImage: windows-latest

# can change it to vmImage: "windows-latest"

# Microsoft-hosted agents already include SDKs and tools for various development languages

#Single step to run the Mavern task
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
